export const ActionType = {
  ADD_ALERT: "ADD_ALERT",
  DELETE_STUFF: "DELETE_STUFF",
  ADD_STUFF: "ADD_STUFF",
  UPDATE_STUFF: "UPDATE_STUFF",
  SWITCH_STUFF_FORM_STATUS: "SWITCH_STUFF_FORM_STATUS",
  SET_STUFF_FORM_DEFAULT_VALUE: "SET_STUFF_FORM_DEFAULT_VALUE",
  OPEN_MODAL: "OPEN_MODAL",
  DELETE_MODAL: "DELETE_MODAL",
};
